version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=microblogging
    ports:
      - '5435:5432'

  app:
    build: .
    ports:
      - '8000:8000'
    command: >
      sh -c 'python3 ./src/microblogging/manage.py migrate &&
      python3 ./src/microblogging/manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
